### ISSUE TITLE
Change to proper data types (removal of magic numbers + lists)

### ISSUE THREAD

**Issue by MrTyton** [coderwilson/FFX_TAS_Python#201]
A large amount of the code relies on lists, extracting different state data based on the length, as well as magic numbers for things like items/maps/encounters/characters.

Status that is stored in lists (hp, requirements for continuing, etc.) should be done in dictionaries instead, for readability.

Magic numbers should be mapped to either enum values if they are used a lot (items, characters), or left only within the function that they are being called in and transformed to a dict->value (like, item quantity) or not referenced outside of their funcs (current menu, for instance)

**Comment by coderwilson** [comment]
Two files I have been using with magic numbers are below. These can be converted to use-able code instead of Google sheets.

https://docs.google.com/spreadsheets/d/1X4Xbsm7NDsPmo9iGZn5zXoaoQg1fGh94ttV6tRI3g3I/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1Kl617v2IjoF1cQUeoH_hVrWeXcKWOgf2pPYt629EXwo/edit?usp=sharing
